### PR TITLE
Card

### PR DESCRIPTION
**Pull request by prathameshpcodes**

### CODE REVIEW

**Review by tanishk15sharma — APPROVED** [review]
good to merge

**Review by tewarimohit — APPROVED** [review]
Looks good to merge...

**Comment by kaustubh-jsr** [comment]
The code is well formatted, and good use of utility classes you have there. This looks good to me.

**Review by kaustubh-jsr — APPROVED** [review]

**Comment by prathameshpcodes** [comment]
@kaustubh-jsr Thanks

**Pull request merged**
